name: CI-CD-Pipeline-to-AWS

env:
  EB_PACKAGE_S3_BUCKET_NAME : "elasticbeanstalk-us-east-1-383734295310"
  EB_APPLICARION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "NyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-1"
  
on:
    push:
        branches: main
  
jobs:
  my_si_part:
    runs-on: ubuntu-latest
   
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v3
 
    - name: Create ZIp deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id        : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key    : ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region               : ${{ env.AWS_REGION_NAME }}
        
    - name: Copy Deployment package to S3 backet
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}   s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: Print happy massage for CI finish
      run : echo "CI Pipeline finished successfuly"
      
  my_sd_part:
     runs-on: ubuntu-latest
     needs: [my_si_part]
     
     steps:
     
     - name: Configure my AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id        : ${{ secrets.MY_AWS_ACCESS_KEY }}
         aws-secret-access-key    : ${{ secrets.MY_AWS_SECRET_KEY }}
         aws-region               : ${{ env.AWS_REGION_NAME }}
         
     - name: Create new ElasticBeanstalk Application
       run : |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICARION_NAME }} \
          --source-bundle S3Bucket="${{ env. EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "Ver-${{ github.sha }}" \
          --description "CoimmitSHA-${{ github.sha }}"
      
      
     - name: Deploy new ElasticBeanstalk Application
       run : aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-lable "Ver-${{ github.sha }}"
      
      
      
